name: Exportar las APIs aprobadada por iniciativa de arquitectura de solucion

on: 
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  export-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4